# Generated by Django 3.1.2 on 2020-12-05 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vacancies', '0006_auto_20201204_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='auth.user'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='education',
            field=models.TextField(verbose_name='Образование'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='experience',
            field=models.TextField(verbose_name='Опыт работы'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='status_CHOISES',
            field=models.CharField(choices=[('busy', 'Не ищу работу'), ('open', 'Рассматриваю предложения'), ('find', 'Ищу работу')], max_length=100, verbose_name='Готовность к работе'),
        ),
    ]
